#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$LED_POSTGRES_USER";
    CREATE USER "$ROLL_POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$LED_POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$ROLL_POSTGRES_USER";
    CREATE SCHEMA "$LED_POSTGRES_SCHEMA";
    CREATE SCHEMA "$ROLL_POSTGRES_SCHEMA";
EOSQL